@startuml

hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

left to right direction

entity d_origin {
    PK origin_code
    --
    origin_name
}

entity d_vehicle {
    PK vehicle_code
    --
    FK freicht_type_code
    --
    vehicle_name
}

entity d_freicht_type {
    PK freicht_type_code
    --
    freicht_type_name
}

entity d_container {
    PK container_code
    --
    FK freicht_code
    container_size
    container_type
}

entity d_container_item {
    PK container_code
    PK item_code
    --
    item_pack_qnty
    item_weight
    container_size
    container_type
}

entity d_order_item {
    PK order_code
    PK item_code
    --
    item_weight
    item_price
}

entity d_contract{
    PK contract_code
    --
    contract_num
    contract_dt
}

entity f_inspection {
    PK inspection_code
    --
    FK inspector_code
    FK location_code
    FK surveyor_code
    FK container_code
    FK report_code
    FK act_code
    FK item_code
    FK contract_code
    FK origin_code
    FK vehicle_code
    FK order_part_code
    FK location_code
    FK freicht_type_code
    --
    arrival_dttm
    inspection_dttm
    item_pack_qnty
    item_weight
    inspection_sum
    inspection_plan_dt
    inspection_result
    result_comment
    category_a_perc
    category_b_perc
    category_c_perc
    category_d_perc
    report_path
}

entity d_item {
    PK item_code
    --
    item_name
    item_category
}

entity d_order {
    PK order_code
    --
    FK supplier_code
    FK consignee_code
    --
    order_dt
}

entity d_order_part {
    PK order_part_code
    --
    FK order_code
    FK freight_code
}

entity d_supplier {
    PK supplier_code
    --
    supplier_name
}

entity d_consignee {
    PK consignee_code
    --
    consignee_name
}

entity d_surveyor {
    PK surveyor_code
    --
    surveyor_name
}

entity d_location {
    PK location_code
    --
    location_name
}

entity d_inspector {
    PK inpector_code
    --
    inspector_fio
}

entity d_act{
    PK act_code
    --
    act_number
    act_date
}

entity d_class {
    PK freicht_type_code
    PK supplier_code
    PK item_code
    --
    class_name
    pack_perc
}

f_inspection }o--|| d_origin

f_inspection }o--up|| d_vehicle

f_inspection ||-|{ d_container

f_inspection }|-left|| d_container

d_container }|--|| d_container_item

d_container_item ||--|{ d_item

d_order ||--|{ d_order_item

d_order_item }|--|| d_item

d_order ||-up-|{ d_order_part

f_inspection ||-up-|{ d_order_part

d_order }o--|| d_supplier

d_order }o-up-|| d_consignee

f_inspection }o--|| d_surveyor

f_inspection }o--|{ d_item

d_location ||--o{ f_inspection

d_inspector ||--upo{ f_inspection

d_contract ||--o{ f_inspection

f_inspection ||--|| d_act

d_class }|--|| d_supplier

d_class }|--|| d_freicht_type

d_class }|--|| d_item

d_freicht_type }|--|| d_vehicle

@enduml
 