@startuml name "inspection data vault"
' hide the spot
hide circle

left to right direction

' avoid problems with angled crows feet
skinparam linetype ortho

entity hub_inspection {
    **PK inspection_sk**
    --
    **FK inspection_location_sk**
    **FK surveyor_sk**
    **FK contract_sk**
    **FK supplier_sk**
    **FK consignee_sk**
    **FK item_sk**
    **FK order_part_sk**
    **FK container_sk**
}

entity sat_inspection_plan {
    **PK inspection_sk**
    --
    plan_inspection_dt
    plan_arrival_dt
    load_dttm
    source_id
}

entity hub_freicht {
    **PK inspection_sk**
    --
    **FK country_sk**
    **FK vehicle_sk**
    arrival_dttm
    load_dttm
    source_id
}

entity hub_country {
    country_sk
    --
    country_iso_code
    country_name
    load_dttm
    source_id
}

entity lnk_freicht_country {
    inspection_sk
    country_sk
    --
    load_dttm
    source_id
}

entity hub_vehicle {
    **PK vehicle_sk**
    --
    vehicle_code
    vehicle_name
    vehicle_type
    load_dttm
    source_id
}

entity lnk_freicht_vehicle {
    inspection_sk
    vehicle_sk
    --
    load_dttm
    source_id
}

entity hub_container {
    container_sk
    --
    container_code
    container_size
    container_weight
    --
    load_dttm
    source_id
}

entity lnk_inspection_container {
    inspection_sk
    container_sk
    --
    load_dttm
    source_id
}

entity lnk_freicht_container {
    freicht_sk
    container_sk
    --
    load_dttm
    source_id
}

'entity sat_inspection_sendout{
'    **PK inspection_sk**
'    --
'    sendout_dt
'    load_dttm
'    source_id
'}

entity lnk_container_item {
    container_sk
    item_sk
    --
    container_item_weight
    container_item_pack_qnty
    --
    load_dttm
    source_id
}

entity sat_inspection_report {
    **PK inspection_sk**
    --
    container_num
    inspection_number
    inspection_dttm
    inspection_report_path
    inspection_type
    inspection_result
    inspection_cost
    category_a_perc
    category_b_perc
    category_c_perc
    category_d_perc
    surveyor_comment
    --
    load_dttm
    source_id
}

entity hub_item {
    **PK item_sk**
    --
    **FK item_vendor_sk**
    **FK item_category_sk**
    --
    item_code
    item_barchar_code
    is_social
    is_food
    is_fresh
    is_excise
    --
    load_dttm
    source_id
}

entity hub_location {
    **PK location_sk**
    --
    location_name
    location_type
    --
    load_dttm
    source_id
}

entity lnk_inspection_location{
    **PK inspection_sk**
    **PK location_sk**
    --
    load_dttm
    source_id
}

entity hub_surveyor {
    **PK location_sk**
    --
    surveyor_name
    --
    load_dttm
    source_id
}

entity hub_contract {
    **PK contract_sk**
    --
    contract_number
    contract_dt
    --
    load_dttm
    source_id
}

entity lnk_inspection_contract {
    **PK inspection_sk**
    **PK contract_sk**
    --
    load_dttm
    source_id
}

entity hub_order {
    **PK order_sk**
    --
    order_num
    order_dt
    order_contract_num
    order_contract_dt
    supplier_name
    supplier_code
    --
    load_dttm
    source_id
}

entity lnk_order_item {
    PK order_sk
    PK item_sk
    --
    order_item_qnty
    order_item_price
    --
    load_dttm
    source_id
}

entity hub_order_part {
    **PK order_part_sk**
    --
    **FK order_sk**
    --
    part_code : char(20)
    --
    load_dttm
    source_id
}

'entity fact_sorting {
'    **PK sorting_sk**
'    --
'    **FK inspection_sk**
'    --
'    contractor
'    contract_number
'    contract_dt
'    act_number
'    act_dt
'    load_location
'    sorting_amount
'    sorting_price
'    unit
'    price_per_unit
'    sorting_plan_dt
'    sorting_dt
'    sorting_report_path
'    contractor_comment
'    utilization_perc
'    return_perc
'    sorting_perc
'    acceptance_perc
'    return_qnty
'    utilization_qnty
'}

'sat_inspection_report ||..up[hidden]|| sat_inspection_freicht
'sat_inspection_freicht ||..up[hidden]|| sat_inspection_plan
'sat_inspection_freicht ||.up[hidden]|| sat_inspection_sendout
'sat_inspection_report - hub_inspection
'sat_inspection_freicht - hub_inspection
'sat_inspection_plan - hub_inspection
'sat_inspection_sendout- hub_inspection
'hub_location ||..[hidden]|| hub_country
'hub_surveyor ||..[hidden]|| hub_item
'hub_country ||.down[hidden]|| hub_item
'hub_location ||--o{ lnk_inspection_location
'lnk_inspection_location }o--|| hub_inspection
'hub_country ||--o{ lnk_inspection_country
'lnk_inspection_country }o--|| hub_inspection
'hub_item ||--o{ hub_inspection
'hub_surveyor ||--o{ hub_inspection
'hub_inspection }o--|| lnk_inspection_contract
'lnk_inspection_contract }o--|| hub_contract
'hub_inspection }o--|| hub_order_part
'hub_inspection }o--|| hub_vehicle
'hub_order_part }o--|| fact_order
'hub_country ||.down[hidden]|| hub_item
'hub_inspection ||-o{fact_sorting

hub_freicht -{ lnk_freicht_country
lnk_freicht_country }-left hub_country

hub_freicht --{ lnk_freicht_vehicle
lnk_freicht_vehicle }-- hub_vehicle

hub_freicht --{ lnk_freicht_container
lnk_freicht_container }-- hub_container

hub_inspection -{ lnk_inspection_container
lnk_inspection_container }- hub_container

hub_container -{ lnk_container_item
lnk_container_item }- hub_item

hub_order -{ lnk_order_item
lnk_order_item }- hub_item

hub_order --{ lnk_order_part
lnk_order_part }-- hub_order_part

hub_order_part --{ lnk_order_part_freicht
lnk_order_part_freicht }-- hub_freicht

hub_order --{ lnk_order_supplier
lnk_order_supplier }-- hub_supplier

hub_inspection -left{ lnk_inspection_surveyor
lnk_inspection_surveyor }-left hub_surveyor

hub_inspection --{ lnk_inspection_item
lnk_inspection_item }-- hub_item

hub_inspection --{ lnk_inspection_location
lnk_inspection_location }-- hub_location

hub_inspection --{ lnk_inspection_inspector
lnk_inspection_inspector }-- hub_inspector

hub_inspection --{ sat_inspection_report

@enduml
