@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity Проверка {
Номер проверки
Планируемая дата проверки
Дата проверки
Страна происхождения
Место приемки
Сюрвейер
Договор
Отправитель
Получатель
Заказ
Партия
Позиция
Категория 1
Категория 2
Категория 3
Категория 4
Транспортное средство
Способ доставки
Дата проверки
Дата прибытия
Путь к файлу отчета о проверке
Тип проверки
Результат проверки
Стоимость проверки
}

entity Утилизация {
Компания утилизатор
Номер договора
Дата договора
Номер акта
Дата акта
Позиция
Место утилизации
Объем утилизации
Цена утилизации за единицу
Ед. измерения
Стоимость утилизации
Планируемая дата утилизации
Дата утилизации
Путь к файлу отчета об утилизации
}

@enduml
