@startuml

hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

left to right direction

entity freicht {
    PK freicht_code
    --
    FK origin_code
    FK vehicle_code
    FK order_part_code
    FK location_code
    FK FK freicht_type_code
    --
    arrival_dttm
}

entity origin {
    PK origin_code
    --
    origin_name
}

entity vehicle {
    PK vehicle_code
    --
    FK freicht_type_code
    --
    vehicle_name
}

entity freicht_type {
    freicht_type_code
    --
    freicht_type_name
}

entity container {
    PK container_code
    --
    container_size
    container_type
}

entity container_item {
    PK container_code
    PK item_code
    --
    item_pack_qnty
    item_weight
    container_size
    container_type
}

entity order_item {
    PK order_code
    PK item_code
    --
    item_weight
    item_price
}

entity contract{
    PK contract_code
    --
    contract_num
    contract_dt
}

entity inspection {
    PK inspection_code
    --
    FK inspector_code
    FK location_code
    FK surveyor_code
    FK container_code
    FK report_code
    FK result_code
    FK item_code
    FK contract_code
    --
    inspection_dttm
    item_pack_qnty
    item_weight
    inspection_sum
    inspection_plan_dt
}

entity item {
    PK item_code
    --
    item_name
    item_category
}

entity order {
    PK order_code
    --
    FK supplier_code
    FK consignee_code
    --
    order_dt
}

entity order_part {
    PK order_part_code
    --
    FK order_code
    FK freight_code
}

entity supplier {
    PK supplier_code
    --
    supplier_name
}

entity consignee {
    PK consignee_code
    --
    consignee_name
}

entity surveyor {
    PK surveyor_code
    --
    surveyor_name
}

entity location {
    PK location_code
    --
    location_name
}

entity inspector {
    PK inpector_code
    --
    inspector_fio
}

entity report {
    PK report_code
    --
    FK inspection_code
    --
    category_a_perc
    category_b_perc
    category_c_perc
    category_d_perc
    report_comment
    report_path
}

entity result {
    PK result_code
    --
    FK inspection_code
    --
    inspection_result
    result_comment
    act_number
    act_date
}

entity class {
    PK freicht_type
    PK supplier_code
    PK item_code
    --
    class_name
    pack_perc
}

freicht }o--|| origin

freicht }o--|| vehicle

freicht ||-|{ container

inspection }|-left|| container

container }|--|| container_item

container_item ||--|{ item

order ||--|{ order_item

order_item }|--|| item

order ||-up-|{ order_part

freicht ||-up-|{ order_part

order }o-up-|| supplier

order }o-up-|| consignee

inspection }o--|| surveyor

inspection }o--|{ item

location ||--o{ inspection

location ||--o{ freicht

inspector ||--o{ inspection

contract ||--o{ inspection

inspection ||--|| report

inspection ||--|| result

class }|--|| supplier

class }|--|| freicht_type

class }|--|| item

freicht_type }|-|| freicht

freicht_type }|--|| vehicle

@enduml
 